### ISSUE TITLE
ImportError: cannot import name 'Schema'

### ISSUE THREAD

**Issue by cpicsh** [zhongzhongBaby/FastapiMysqlDemo#1]
(venv) [root@instance-fastapi1 FastApiMysqlDemo]# uvicorn main:app --reload
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [6770] using statreload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.6/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/uvicorn/server.py", line 56, in serve
    config.load()
  File "/usr/local/lib/python3.6/site-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.6/site-packages/uvicorn/importer.py", line 23, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.6/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 2, in <module>
    from course.course_curd import course_router
  File "./course/course_curd.py", line 4, in <module>
    from common.entity import FindRequestBase
  File "./common/entity.py", line 3, in <module>
    from pydantic import BaseModel, Schema, Field
ImportError: cannot import name 'Schema'

**Comment by cpicsh** [comment]
./common/entity.py 删除了Schema 可以运行了，但是调试API接口登录时报：
默认账号 密码 Admin 123456 报Auth ErrorError: Internal Server Error，
数据库是能连接的，默认账号 密码 pxxAdmin 123456 报密码错误
可能是什么问题？

**Comment by cpicsh** [comment]
File "/usr/local/lib/python3.6/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.6/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "./auth.py", line 131, in login_for_access_token
    return {"user_name": user.username, "access_token": "Bearer " + str(access_token, encoding="utf8"),
TypeError: decoding str is not supported
  File "./auth.py", line 131, in login_for_access_token
    return {"user_name": user.username, "access_token": "Bearer " + str(access_token, encoding="utf8"),
TypeError: decoding str is not supported

**Comment by zhongzhongBaby** [comment]
> return {"user_name": user.username, "access_token": "Bearer " + str(access_token, encoding="utf8"),
> TypeError: decoding str is not supported

看日志是编码方式问题，可以打印一下你系统的编码，或者去掉encoding="utf8"试试。
